### ISSUE TITLE
cf.bu-workshop.template.j2 - hardcoded values

### ISSUE THREAD

**Issue by kenthua** [thoraxe/ansible_aws_deployer#6]
KeyName for each node type hardcoded to: "roadshow".  Use the "roadshow" key name or replace with your own.

"HostedZoneId" for route53 needs to be changed to your specific HostedZoneId in route 53.

**Comment by thoraxe** [comment]
Yeah -- either edit yourself for now or these can be parameterized later.

I had added the zoneid to the readme. I don't think I added the keyname.
