### ISSUE TITLE
ansible errors out on duplicate dict / variable values in bu-workshop_vars.yml

### ISSUE THREAD

**Issue by kenthua** [thoraxe/ansible_aws_deployer#7]
"install_metrics" and "repo_version" are duplicated in the file and errors out during execution

need to comment out the duplicates, unless there is a specific reason for having it repeat

**Comment by thoraxe** [comment]
What version of Ansible? It doesn't fail out for me on 2.1.2.

But yeah if they're dupes go ahead and PR them out.

**Comment by kenthua** [comment]
ansible 2.2.0, maybe they added a new check

**Comment by thoraxe** [comment]
https://github.com/sborenst/ansible_aws_deployer/issues/7
