### ISSUE TITLE
missing nfs host on a bu-workshop run

### ISSUE THREAD

**Issue by kenthua** [thoraxe/ansible_aws_deployer#8]
Looks like the template is trying to generate host file, the nfs entry is missing?

TASK [generate ansible hosts file] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'nfs'"}

http://pastebin.com/aa10Mgsm

**Comment by thoraxe** [comment]
What's the syntax you're using to launch what playbook? Can you show the commandline? Your paste is just Ansible output.

I was getting this when I had modified the hosts template and removed the NFS group but was still doing something else with the original playbook.

**Comment by kenthua** [comment]
ansible-playbook -i 127.0.0.1 ansible/bu-workshop.yml -e "config=bu-workshop" -e "aws_region=us-west-1" -e "guid=test"

**Comment by thoraxe** [comment]
switch to https://github.com/sborenst/ansible_aws_deployer

I am guessing you're using some old checkout or branch of my thing and it's not working. I'm not seeing that problem.

Switch to filing issues over there.
